copy 0.mob ..\new\mob\
copy 1.mob ..\new\mob\
copy 2.mob ..\new\mob\
copy 3.mob ..\new\mob\
copy 10.mob ..\new\mob\
copy 12.mob ..\new\mob\
copy 16.mob ..\new\mob\
copy 19.mob ..\new\mob\
copy 20.mob ..\new\mob\
copy 22.mob ..\new\mob\
copy 23.mob ..\new\mob\
copy 24.mob ..\new\mob\
copy 25.mob ..\new\mob\
copy 28.mob ..\new\mob\
copy 30.mob ..\new\mob\
copy 31.mob ..\new\mob\
copy 33.mob ..\new\mob\
copy 34.mob ..\new\mob\
copy 35.mob ..\new\mob\
copy 37.mob ..\new\mob\
copy 40.mob ..\new\mob\
copy 47.mob ..\new\mob\  
copy 50.mob ..\new\mob\
copy 51.mob ..\new\mob\
copy 52.mob ..\new\mob\
copy 60.mob ..\new\mob\
copy 61.mob ..\new\mob\
copy 62.mob ..\new\mob\
copy 63.mob ..\new\mob\
copy 64.mob ..\new\mob\
copy 65.mob ..\new\mob\
copy 66.mob ..\new\mob\
copy 70.mob ..\new\mob\
copy 72.mob ..\new\mob\
copy 79.mob ..\new\mob\
copy 82.mob ..\new\mob\
copy 83.mob ..\new\mob\
copy 89.mob ..\new\mob\
copy 99.mob ..\new\mob\
copy 101.mob ..\new\mob\
copy 115.mob ..\new\mob\  
copy 125.mob ..\new\mob\
copy 143.mob ..\new\mob\
copy 170.mob ..\new\mob\
copy 186.mob ..\new\mob\
copy 190.mob ..\new\mob\
copy 192.mob ..\new\mob\
copy 195.mob ..\new\mob\
copy 196.mob ..\new\mob\
copy 200.mob ..\new\mob\
copy 201.mob ..\new\mob\
copy 220.mob ..\new\mob\
copy 225.mob ..\new\mob\
copy 230.mob ..\new\mob\
copy 231.mob ..\new\mob\
copy 300.mob ..\new\mob\
$
