copy 0.zon ..\new\zon
copy 1.zon ..\new\zon
copy 2.zon ..\new\zon
copy 3.zon ..\new\zon
copy 10.zon ..\new\zon
copy 12.zon ..\new\zon
copy 16.zon ..\new\zon
copy 17.zon ..\new\zon
copy 19.zon ..\new\zon
copy 20.zon ..\new\zon
copy 22.zon ..\new\zon
copy 23.zon ..\new\zon
copy 24.zon ..\new\zon
copy 25.zon ..\new\zon
copy 26.zon ..\new\zon
copy 28.zon ..\new\zon
copy 30.zon ..\new\zon
copy 31.zon ..\new\zon
copy 33.zon ..\new\zon
copy 34.zon ..\new\zon
copy 35.zon ..\new\zon
copy 37.zon ..\new\zon
copy 40.zon ..\new\zon
copy 41.zon ..\new\zon
copy 47.zon ..\new\zon
copy 50.zon ..\new\zon
copy 51.zon ..\new\zon
copy 52.zon ..\new\zon
copy 60.zon ..\new\zon
copy 61.zon ..\new\zon
copy 62.zon ..\new\zon
copy 63.zon ..\new\zon
copy 64.zon ..\new\zon
copy 65.zon ..\new\zon
copy 66.zon ..\new\zon
copy 70.zon ..\new\zon
copy 71.zon ..\new\zon
copy 72.zon ..\new\zon
copy 73.zon ..\new\zon
copy 79.zon ..\new\zon
copy 82.zon ..\new\zon
copy 83.zon ..\new\zon
copy 89.zon ..\new\zon
copy 99.zon ..\new\zon
copy 101.zon ..\new\zon
copy 115.zon ..\new\zon
copy 125.zon ..\new\zon
copy 143.zon ..\new\zon
copy 170.zon ..\new\zon
copy 186.zon ..\new\zon
copy 190.zon ..\new\zon
copy 192.zon ..\new\zon
copy 195.zon ..\new\zon
copy 196.zon ..\new\zon
copy 200.zon ..\new\zon
copy 201.zon ..\new\zon
copy 220.zon ..\new\zon
copy 225.zon ..\new\zon
copy 230.zon ..\new\zon
copy 231.zon ..\new\zon
copy 240.zon ..\new\zon
copy 250.zon ..\new\zon
copy 251.zon ..\new\zon
copy 252.zon ..\new\zon
copy 300.zon ..\new\zon
$
