A request was entered at Lands of Myst MUD to create
a new character for this email address. If this is
indeed the case, then can use the following data
to log your new character.

Name    : Bibo
Password: fsqnqcxu


- You can always change your password (press '4' in
  the main menu).
- If this is your first character in LOM it
  is advisable that you type 'help newbie' once you
  enter the mud world.

Have fun!





* Lands of Myst MUD
* 148.251.247.173 4000
