copy 0.wld ..\new\wld
copy 2.wld ..\new\wld
copy 3.wld ..\new\wld
copy 10.wld ..\new\wld
copy 12.wld ..\new\wld
copy 16.wld ..\new\wld
copy 19.wld ..\new\wld
copy 20.wld ..\new\wld
copy 22.wld ..\new\wld
copy 23.wld ..\new\wld
copy 24.wld ..\new\wld
copy 25.wld ..\new\wld
copy 28.wld ..\new\wld
copy 30.wld ..\new\wld
copy 31.wld ..\new\wld
copy 33.wld ..\new\wld
copy 34.wld ..\new\wld
copy 35.wld ..\new\wld
copy 37.wld ..\new\wld
copy 40.wld ..\new\wld
copy 47.wld ..\new\wld
copy 50.wld ..\new\wld
copy 51.wld ..\new\wld
copy 52.wld ..\new\wld
copy 60.wld ..\new\wld
copy 61.wld ..\new\wld
copy 62.wld ..\new\wld
copy 63.wld ..\new\wld
copy 64.wld ..\new\wld
copy 65.wld ..\new\wld
copy 66.wld ..\new\wld
copy 70.wld ..\new\wld
copy 71.wld ..\new\wld
copy 72.wld ..\new\wld
copy 79.wld ..\new\wld
copy 82.wld ..\new\wld
copy 83.wld ..\new\wld
copy 89.wld ..\new\wld
copy 99.wld ..\new\wld
copy 101.wld ..\new\wld
copy 115.wld ..\new\wld  
copy 125.wld ..\new\wld
copy 143.wld ..\new\wld
copy 170.wld ..\new\wld
copy 186.wld ..\new\wld
copy 190.wld ..\new\wld
copy 192.wld ..\new\wld
copy 194.wld ..\new\wld
copy 195.wld ..\new\wld
copy 196.wld ..\new\wld
copy 200.wld ..\new\wld
copy 201.wld ..\new\wld
copy 220.wld ..\new\wld
copy 225.wld ..\new\wld
copy 230.wld ..\new\wld
copy 231.wld ..\new\wld
copy 240.wld ..\new\wld
copy 251.wld ..\new\wld
copy 252.wld ..\new\wld
copy 300.wld ..\new\wld
$
